#ifndef __CORE_CARD_H
#define __CORE_CARD_H
#include "../utils/all.h"
#include "types.h"

Card deck[80] = {{.type = Bang, .priority = 101, .use = NULL},
                 {.type = Bang, .priority = 201, .use = NULL},
                 {.type = Bang, .priority = 212, .use = NULL},
                 {.type = Bang, .priority = 213, .use = NULL},
                 {.type = Bang, .priority = 301, .use = NULL},
                 {.type = Bang, .priority = 301, .use = NULL},
                 {.type = Bang, .priority = 302, .use = NULL},
                 {.type = Bang, .priority = 303, .use = NULL},
                 {.type = Bang, .priority = 304, .use = NULL},
                 {.type = Bang, .priority = 305, .use = NULL},
                 {.type = Bang, .priority = 306, .use = NULL},
                 {.type = Bang, .priority = 307, .use = NULL},
                 {.type = Bang, .priority = 308, .use = NULL},
                 {.type = Bang, .priority = 309, .use = NULL},
                 {.type = Bang, .priority = 310, .use = NULL},
                 {.type = Bang, .priority = 311, .use = NULL},
                 {.type = Bang, .priority = 312, .use = NULL},
                 {.type = Bang, .priority = 313, .use = NULL},
                 {.type = Bang, .priority = 402, .use = NULL},
                 {.type = Bang, .priority = 403, .use = NULL},
                 {.type = Bang, .priority = 404, .use = NULL},
                 {.type = Bang, .priority = 405, .use = NULL},
                 {.type = Bang, .priority = 406, .use = NULL},
                 {.type = Bang, .priority = 407, .use = NULL},
                 {.type = Bang, .priority = 408, .use = NULL},
                 {.type = Bang, .priority = 409, .use = NULL},
                 {.type = Missed, .priority = 102, .use = NULL},
                 {.type = Missed, .priority = 103, .use = NULL},
                 {.type = Missed, .priority = 104, .use = NULL},
                 {.type = Missed, .priority = 105, .use = NULL},
                 {.type = Missed, .priority = 106, .use = NULL},
                 {.type = Missed, .priority = 107, .use = NULL},
                 {.type = Missed, .priority = 108, .use = NULL},
                 {.type = Missed, .priority = 401, .use = NULL},
                 {.type = Missed, .priority = 410, .use = NULL},
                 {.type = Missed, .priority = 411, .use = NULL},
                 {.type = Missed, .priority = 412, .use = NULL},
                 {.type = Missed, .priority = 413, .use = NULL},
                 {.type = Gatling, .priority = 210, .use = NULL},
                 {.type = Indians, .priority = 301, .use = NULL},
                 {.type = Indians, .priority = 313, .use = NULL},
                 {.type = Panic, .priority = 201, .use = NULL},
                 {.type = Panic, .priority = 211, .use = NULL},
                 {.type = Panic, .priority = 212, .use = NULL},
                 {.type = Panic, .priority = 308, .use = NULL},
                 {.type = Cat_Balou, .priority = 213, .use = NULL},
                 {.type = Cat_Balou, .priority = 309, .use = NULL},
                 {.type = Cat_Balou, .priority = 310, .use = NULL},
                 {.type = Cat_Balou, .priority = 311, .use = NULL},
                 {.type = Stagecoach, .priority = 109, .use = NULL},
                 {.type = Stagecoach, .priority = 109, .use = NULL},
                 {.type = Wells_Fargo, .priority = 203, .use = NULL},
                 {.type = General_Store, .priority = 112, .use = NULL},
                 {.type = General_Store, .priority = 409, .use = NULL},
                 {.type = Beer, .priority = 206, .use = NULL},
                 {.type = Beer, .priority = 207, .use = NULL},
                 {.type = Beer, .priority = 208, .use = NULL},
                 {.type = Beer, .priority = 209, .use = NULL},
                 {.type = Beer, .priority = 210, .use = NULL},
                 {.type = Beer, .priority = 211, .use = NULL},
                 {.type = Saloon, .priority = 205, .use = NULL},
                 {.type = Duel, .priority = 111, .use = NULL},
                 {.type = Duel, .priority = 312, .use = NULL},
                 {.type = Duel, .priority = 408, .use = NULL},
                 {.type = Barrel, .priority = 112, .use = NULL},
                 {.type = Barrel, .priority = 113, .use = NULL},
                 {.type = Scope, .priority = 101, .use = NULL},
                 {.type = Mustang, .priority = 208, .use = NULL},
                 {.type = Mustang, .priority = 209, .use = NULL},
                 {.type = Jail, .priority = 110, .use = NULL},
                 {.type = Jail, .priority = 111, .use = NULL},
                 {.type = Jail, .priority = 204, .use = NULL},
                 {.type = Dynamite, .priority = 202, .use = NULL},
                 {.type = Volcanic, .priority = 110, .use = NULL},
                 {.type = Volcanic, .priority = 410, .use = NULL},
                 {.type = Schofield, .priority = 113, .use = NULL},
                 {.type = Schofield, .priority = 411, .use = NULL},
                 {.type = Schofield, .priority = 412, .use = NULL},
                 {.type = Remington, .priority = 413, .use = NULL},
                 {.type = Rev_Carabine, .priority = 401, .use = NULL},
                 {.type = Winchester, .priority = 108, .use = NULL}}

#endif  // __CORE_CARD_H