name: Pull Request Checker

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "**/*.md"

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Lint
              uses: DoozyX/clang-format-lint-action@v0.13
              with:
                  clangFormatVersion: 13
                  exclude: ./src/third/*

            - name: Setup
              run: sudo make setup

            - name: Build
              run: make -j4

            - name: Build Server
              run: make server
