---
printWidth: 100
tabWidth: 4
useTabs: false
trailingComma: all
semi: true
singleQuote: false
overrides:
  - files: "**/*.{md,yml}"
    options:
      tabWidth: 2
# plugins:
# - "./node_modules/prettier-plugin-tailwindcss/dist/index.js"
